export default () => ({
  app: {
    NODE_ENV: process.env.NODE_ENV || 'development',
    MONGO_URL: process.env.MONGO_URL || 'mongodb://mongo:27017/test?replicaSet=rs0',
    ENCRYPTION_KEY: process.env.ENCRYPTION_KEY,
    JWT_ACCESS_SECRET: process.env.JWT_ACCESS_SECRET,
    JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
    JWT_SECRET_KEY: process.env.JWT_SECRET_KEY,
    REDIS_HOST: process.env.REDIS_HOST || 'localhost',
    REDIS_PORT: parseInt(process.env.REDIS_PORT ?? '6379', 10),
    OTP_TTL: parseInt(process.env.OTP_TTL ?? '300', 10),
    SUPERADMIN_PHONE: process.env.SUPERADMIN_PHONE,
    SUPERADMIN_MELICODE: process.env.SUPERADMIN_MELICODE,
    ZIBAL_MERCHANT_ID: process.env.ZIBAL_MERCHANT_ID || '68b44a2ca45c720011a852e0',
    ZIBAL_SANDBOX: (process.env.ZIBAL_SANDBOX || '').toLowerCase() === 'true',
    ZIBAL_CALLBACK_URL: process.env.ZIBAL_CALLBACK_URL || 'http://localhost:3000/payment/callback',
    ZIBAL_SECRET_KEY: process.env.ZIBAL_SECRET_KEY || '',
    ZIBAL_LOG_LEVEL: parseInt(process.env.ZIBAL_LOG_LEVEL || '2', 10),
    APP_URL: process.env.APP_URL || 'http://localhost:3000',
    R2_ENDPOINT: process.env.R2_ENDPOINT,
    R2_ACCESS_KEY: process.env.R2_ACCESS_KEY,
    R2_SECRET_KEY: process.env.R2_SECRET_KEY,
    R2_BUCKET: process.env.R2_BUCKET,
    R2_PUBLIC_BASE_URL: process.env.R2_PUBLIC_BASE_URL,
  },
});
