export const IMAGE_UPLOAD_TOKEN = {
  S3_CLIENT: 'R2_S3_CLIENT',
};

export const DEFAULTS = {
  PRESIGN_EXPIRES_SECONDS: 300, // 5 minutes
  MAX_IMAGE_BYTES: 100 * 1024, // 100 KB
  MAX_PRODUCT_IMAGES: 5,
  MAX_COMPANY_IMAGES: 1,
};
