export enum Resource {
  CARTS = 'carts',
  CATEGORIES = '',
  COMPANIES = '',
  ORDERS = '',
  PAYMENT = '',
  PRODUCTS = '',
  ROLES = '',
  TICKETING = '',
  TRANSACTION = '',
  TRANSPORTING = '',
  USERS = '',
  WALLETS = '',
  ALL = 'all',
}
